#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
$schema: "https://spec.openapis.org/oas/3.1/dialect/base"
openapi: 3.1.0

info:
  title: 'admin-models'
  description: 'Tailormap admin API models'
  version: '1.0'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

components:
  schemas:
    ServerSentEvent:
      description: 'Server sent event'
      type: object
      properties:
        eventType:
          type: string
          description: 'Type of event'
          enum: [ 'keep-alive', 'entity-created', 'entity-deleted', 'entity-updated' ]
        details:
          type: object

    EntityEvent:
      type: object
      properties:
        entityName:
          type: string
        id:
          type: string
        object:
          description: 'The entity in JSON, only included in created and updated events.'
          type: object
