#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3
info:
  title: 'models'
  description: 'Tailormap API models common to the persistence layer and the API.'
  version: '1.0'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'

# no servers or paths, just the models in this document
servers: [ ]
paths: { }

# The openapi-generator plugin is run twice: once for the persistence layer JSON and once for the
# models used in the API. Specify all common models in <importMappings> for the second run so common
# models use the same class, and add them to the common-schemas-openapi-ignore file.

components:
  schemas:
    GeoServiceProtocol:
      type: string
      enum:
        - wms
        - wmts
        - xyz
    TileLayerHiDpiMode:
      type: string
      enum:
        # Tiles are DPI-independent, for example an orthofoto - just show the next zoom level at
        # high DPI.
        - showNextZoomLevel
        # Substitute a layer which renders features larger (using more pixels for lines, labels,
        # etc.) but show a deeper zoomlevel of the substituted layer.
        - substituteLayerShowNextZoomLevel
        # Show the same zoomlevel of the substituted layer but set tilePixelRatio to 2: the layer
        # must be a 2x sized tile compared to the size in the capabilities
        - substituteLayerTilePixelRatioOnly

    Bounds:
      type: object
      properties:
        miny:
          description: 'lower bottom'
          type: number
          format: double
        minx:
          description: 'lower left'
          type: number
          format: double
        maxy:
          description: 'upper top'
          type: number
          format: double
        maxx:
          description: 'upper right'
          type: number
          format: double
      required:
        - miny
        - minx
        - maxy
        - maxx
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000

    # XXX: currently unused
    BoundsWithCRS:
      description: 'Bounds within the context of a coordinate reference system'
      allOf:
        - $ref: '#/components/schemas/Bounds'
        - type: object
          required: [crs]
          properties:
            crs:
              description: '(EPSG) code of the projection'
              type: string
              nullable: false
      example:
        miny: 400000
        minx: 105000
        maxy: 530000
        maxx: 275000
        crs: 'EPSG:28992'

    TMGeometryType:
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point

    TMAttributeType:
      description: 'data type. eg "date" or "string".
          see also: nl.tailormap.api.persistence.TMAttributeDescriptor'
      type: string
      enum:
        - geometry
        - geometry_collection
        - multipolygon
        - polygon
        - multilinestring
        - linestring
        - multipoint
        - point
        - boolean
        - integer
        - string
        - double
        - date
        - timestamp
        - object

    WMSStyle:
      type: object
      required: [name]
      properties:
        name:
          type: string
          nullable: false
        title:
          type: string
        abstractText:
          type: string
        legendURL:
          type: string
          format: uri

    AppI18nSettings:
      title: AppI18nSettings
      type: object
      required:
        - defaultLanguage
        - hideLanguageSwitcher
      properties:
        defaultLanguage:
          type: string
          nullable: true
        hideLanguageSwitcher:
          nullable: false
          type: boolean

    AppUiSettings:
      title: AppUiSettings
      type: object
      required:
        - hideLoginButton
      properties:
        hideLoginButton:
          nullable: false
          type: boolean