#
# Copyright (C) 2023 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3

info:
  title: 'persistence-schemas'
  description: 'Schemas used for JSON persistence.'
  version: '1.0'

servers: [ ]
paths: { }

components:
  schemas:
    GeoServiceProtocol:
      $ref: './common-schemas.yaml#/components/schemas/GeoServiceProtocol'

    CatalogNode:
      description: Categorization for items in the catalog.
      properties:
        id:
          type: string
        title:
          type: string
        root:
          type: boolean
        children:
          type: array
          items:
            type: string
        items:
          type: array
          items:
            title: TailormapObjectRef
            type: object
            properties:
              kind:
                type: string
                enum: ['geo-service', 'feature-source', 'app']
              id:
                type: string

    TMServiceCaps:
      type: object
      properties:
        serviceInfo:
          title: TMServiceInfo
          type: object
          properties:
            title:
              type: string
            keywords:
              type: array
              items:
                type: string
              uniqueItems: true
            description:
              type: string
            publisher:
              type: string
              format: uri
            schema:
              type: string
              format: uri
            source:
              type: string
              format: uri
        capabilities:
          type: object
          properties:
            version:
              type: string
            updateSequence:
              type: string
            abstractText:
              type: string
            request:
              title: TMServiceCapabilitiesRequest
              type: object
              properties:
                get-map:
                  type: object
                  properties:
                    formats:
                      type: array
                      items:
                        type: string
                      uniqueItems: true
                get-feature-info:
                  title: TMServiceCapabilitiesRequestGetFeatureInfo
                  type: object
                  properties:
                    formats:
                      type: array
                      items:
                        type: string
                      uniqueItems: true
                describe-layer:
                  type: boolean

    TMFeatureTypeInfo:
      type: object
      properties:
        keywords:
          type: array
          items:
            type: string
          uniqueItems: true
        description:
          type: string
        publisher:
          type: string
          format: uri
        schema:
          type: string
          format: uri
        source:
          type: string
          format: uri
        bounds:
          $ref: './common-schemas.yaml#/components/schemas/Bounds'
        crs:
          type: string
        wgs84BoundingBox:
          $ref: './common-schemas.yaml#/components/schemas/Bounds'
        defaultSrs:
          type: string
        otherSrs:
          items:
            type: string
          uniqueItems: true
        outputFormats:
          items:
            type: string
          uniqueItems: true
        abstractText:
          type: string

    TMGeometryType:
      $ref: './common-schemas.yaml#/components/schemas/TMGeometryType'

    TMAttributeType:
      $ref: './common-schemas.yaml#/components/schemas/TMAttributeType'

    TMAttributeDescriptor:
      properties:
        name:
          type: string
        comment:
          type: string
          description: Comment from the source, if available (such as database comment) [TODO]
        type:
          $ref: './common-schemas.yaml#/components/schemas/TMAttributeType'
        unknownTypeClassName:
          type: string
          description: Class name of type (as produced by GeoTools DataStore) which isn't in the
            type enum list and thus unknown. When the type is 'object' this should contain the full
            class-name, mostly for debugging purposes so the type may be added to the enum list.
        nullable:
          type: boolean
        description:
          type: string

    ServiceAuthentication:
      properties:
        method:
          type: string
          enum:
            - password
        username:
          type: string
        password:
          type: string

    JDBCConnectionProperties:
      type: object
      properties:
        dbtype:
          type: string
          enum:
            - postgis
            - oracle
            - sqlserver
        database:
          type: string
        port:
          type: integer
          nullable: false
        host:
          type: string
        schema:
          type: string
        fetchSize:
          type: integer
        primaryKeyMetadataTable:
          type: string
        geometryMetadataTable:
          type: string
        additionalProperties:
          type: object
          additionalProperties:
            type: string

    GeoServiceSettings:
      description: Settings applying to a GeoService.
      properties:
        serverType:
          description: Server type to use for vendor-specific capabilities (high DPI, legends, etc.)
          type: string
          enum:
            - auto
            - disabled
            - geoserver
            - mapserver
          nullable: false
          default: auto
        useProxy:
          type: boolean
          nullable: false
          default: false
        publishing:
          title: ServicePublishingSettings
          type: object
          properties:
            baseApp:
              type: string
            defaultProjection:
              type: string
            projections:
              type: array
              items:
                type: string
        defaultLayerSettings:
          title: GeoServiceDefaultLayerSettings
          description: Default settings for all layers of this service which can be overridden on a per-layer basis.
          anyOf:
            - $ref: '#/components/schemas/LayerSettings'
            - $ref: '#/components/schemas/WMSLayerSettings'
            - $ref: '#/components/schemas/WMTSLayerSettings'
          default:
        layerSettings:
          title: GeoServiceLayerSettings
          type: object
          additionalProperties:
            anyOf:
              - $ref: '#/components/schemas/LayerSettings'
              - $ref: '#/components/schemas/WMSLayerSettings'
              - $ref: '#/components/schemas/WMTSLayerSettings'
          example:
            'begroeidterreindeel':
              title: laag 1
            'begroeidterreindeel_2':
              title: laag 2
            'otherLayer':
              hiDpiDisabled: true

    LayerSettings:
      description: Settings applying to any kind of layer.
      properties:
        title:
          description: Override default title, null if not overridden.
          type: string
        hiDpiDisabled:
          type: boolean
          default: false
        featureType:
          $ref: FeatureTypeRef

    FeatureTypeRef:
      required: [featureSourceId, featureTypeName]
      properties:
        featureSourceId:
          type: integer
          format: int64
          nullable: false
        featureTypeName:
          type: string
          nullable: false

    WMSLayerSettings:
      description: Settings applying to a WMS layer.
      allOf:
        - $ref: '#/components/schemas/LayerSettings'
        - type: object
          required: [tilingDisabled, tilingGutter]
          properties:
            tilingDisabled:
              type: boolean
              default: false
            tilingGutter:
              type: integer
              # TODO: set global default here or in frontend?

    WMTSLayerSettings:
      description: Settings applying to a WMTS layer.
      allOf:
        - $ref: '#/components/schemas/LayerSettings'
        - type: object
          properties:
            hiDpiMode:
              $ref: './common-schemas.yaml#/components/schemas/TileLayerHiDpiMode'
            hiDpiSubstituteLayer:
              description: Layer name of this service to substitute when rendering at high dpi.
              type: string

    GeoServiceLayer:
      description: Layer of a service which can be an OGC WMS/WMTS service or from XYZ/ArcGIS REST.
      required: [name, root, virtual, children]
      properties:
        # TODO: heeft een WMS virtual grouplayer wel een naam?
        name:
          type: string
        root:
          type: boolean
        title:
          type: string
        virtual:
          type: boolean
        maxScale:
          type: number
          format: double
        minScale:
          type: number
          format: double
        crs:
          description: Only the CRSes added by this layer, all parent CRSes are inherited.
          type: array
          uniqueItems: true
          items:
            type: string
        latLonBoundingBox:
          $ref: './common-schemas.yaml#/components/schemas/Bounds'
        styles:
          type: array
          items:
            $ref: './common-schemas.yaml#/components/schemas/WMSStyle'
        queryable:
          type: boolean
        attribution:
          type: string
        abstractText:
          type: string
        children:
          type: array
          items:
            # layer name
            type: string

    AppTreeNode:
      description: Abstract base schema for nodes in tree.
      type: object
      properties:
        id:
          description: A unique identifier across all tree nodes.
          type: string
        description:
          description: Description for this node entered by application admin.
          type: string
      required:
        - id

    AppTreeFolderNode:
      description: Node for organizing app layer referencing nodes in a folder tree.
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/AppTreeNode'
        - type: object
          properties:
            title:
              description: Display title of this tree node.
              type: string
            root:
              description: Only a single node in a tree will have this set to true.
              type: boolean
            childrenIds:
              description: Ordered list of ids of LayerTreeNodes that are children of this node.
              type: array
              items:
                type: string
          required:
            - root
            - title

    AppTreeLayerNode:
      description: Node referencing a layer.
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/AppTreeNode'
        - type: object
          properties:
            serviceId:
              type: string
            layerName:
              type: string
              nullable: false
            visible:
              type: boolean
              description: Whether this layer should be shown on the map on startup.
              nullable: false
              default: true
          required:
            - serviceId
            - layerName

    # TODO: slimmigheden zoals ook nieuwe lagen opnemen met defaults, default configs, etc.
    AppContent:
      description: Configuration for including content (layers) in an application.
      properties:
        baseLayerNodes:
#          title: BaseLayer
          type: array
          items:
            $ref: '#/components/schemas/AppTreeNode'
        layerNodes:
          type: array
          items:
            $ref: '#/components/schemas/AppTreeNode'

    AppSettings:
      description: Settings applying to a viewer application.
      properties:
        layerSettings:
          title: AppLayerSettings
          description: Map of id of an AppTreeLayerNode to its' settings.
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AppLayerSettings'

    AppLayerSettings:
      properties:
        title:
          type: string
        opacity:
          type: integer
          nullable: false
          default: 100
        # TODO add properties for selected WMS style, feature info popup template, etc.