version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 25
    target-branch: main
    reviewers:
      - mprins
    assignees:
      - mprins
    labels:
      - infrastucture
      - dependency
    # we need to stay on springboot 2.7.x / spring-security 5.8.x / hibernate 5.6.x
    # at least until geotools has moved to the new Jakarta EE api
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        versions:
          - '>= 3'
      - dependency-name: org.springframework.security:spring-security-crypto
        versions:
          - '>= 6'
      - dependency-name: org.hibernate.orm.tooling:hibernate-enhance-maven-plugin
        versions:
          - '>= 6'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "21:00"
      timezone: Europe/Amsterdam
    assignees:
      - mprins
    labels:
      - infrastucture

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "21:00"
      timezone: Europe/Amsterdam
    target-branch: main
    reviewers:
      - mprins
    assignees:
      - mprins
    labels:
      - infrastucture
    ignore:
      # stay on Java 11 for now
      - dependency-name: "eclipse-temurin"
        versions:
          - ">= 12"
