#
# Copyright (C) 2021 B3Partners B.V.
#
# SPDX-License-Identifier: MIT
#
openapi: 3.0.3

info:
  title: 'status responses'
  description: 'Tailormap status API decribes generic responses.'
  contact:
    name: 'B3Partners BV'
    url: 'https://www.b3partners.nl/'
    email: 'info@b3partners.nl'
  license:
    name: 'MIT'
    url: 'https://mit-license.org/'
  version: '1.0'

# none; specified in tailormap-api.yaml
servers: [ ]
# none; specified in tailormap-api.yaml
paths: { }

components:
  schemas:
    RedirectResponse:
      description: '
      login required response, but can also be used for other response that require redirection.
      Does not include a HTTP header to force redirection, but a url that the client can use.
      '
      type: object
      properties:
        code:
          type: integer
          format: int32
          default: 401
        url:
          description: 'redirect url'
          type: string
          default: '/login'
      example:
        code: 401
        message: 'login required'
        url: '/login'


    ErrorResponse:
      description: '
      General server error response. Can be returned when something goes terribly wrong in the backend.
      **Note** that the diagnostic message may be of a general character to prevent disclosure of information about the backend.
      Error codes are defined in the [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) standard, 
      and can range from 400 to 599.
      '
      type: object
      properties:
        code:
          type: integer
          format: int32
          default: 500
        message:
          description: 'diagnostic message'
          type: string
          default: 'Internal server error'
      example:
        code: 500
        message: 'Internal server error'
