name: "Cleanup and Maintainance"

on:
  workflow_dispatch:
  schedule:
    - cron: "19 23 * * 1"

concurrency: # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
#  dockercleanup:
#    runs-on: ubuntu-latest
#    name: "Pruning Untagged Images"
#    steps:
#      - name: "Older than 1 week"
#        # https://github.com/marketplace/actions/ghcr-pruning
#        uses: vlaurin/action-ghcr-prune@v0.6.0
#        with:
#          token: ${{ secrets.GHCR_CLEANUP_PAT }}
#          organization: Tailormap
#          container: tailormap-api
#          dry-run: false
#          keep-younger-than: 7
#          keep-last: 1
#          prune-untagged: true
#      - name: "Older than 4 weeks"
#        uses: vlaurin/action-ghcr-prune@v0.6.0
#        with:
#          token: ${{ secrets.GHCR_CLEANUP_PAT }}
#          organization: Tailormap
#          container: tailormap-api
#          dry-run: false
#          keep-younger-than: 28
#          keep-last: 0
#          prune-untagged: true

  stale:
    runs-on: ubuntu-latest
    name: Close Stale PRs
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 10

  workflows:
    runs-on: ubuntu-latest
    name: Cleanup old workflow runs
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          # same as "Artifact and log retention" in https://github.com/Tailormap/tailormap-api/settings/actions
          retain_days: 90
          keep_minimum_runs: 2
