name: MacOS Maven build

env:
  MAVEN_OPTS: -Djava.awt.headless=true

concurrency:
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build w/ Java 11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Priming build with Maven
        run: mvn -B -V -fae -DskipTests -DskipITs -DskipQA=true install

      - name: Build with Maven
        run: |
          mvn -B -fae -e test
          mvn -B -fae -e verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Cleanup snapshots
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
