name: REUSE Compliance Check

on:
  push:

jobs:
  test:
    name: Check compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
        with:
          args: lint
